apiVersion: apps/v1
kind: Deployment
metadata:
  name: candles
  labels:
    app: candles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candles
  template:
    metadata:
      labels:
        app: candles
    spec:
      containers:
      - name: candles
        image: candles:v1.0.0
        imagePullPolicy: Never # Use the local image
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_INPUT_TOPIC
          value: "trades"
        - name: KAFKA_OUTPUT_TOPIC
          value: "candles"
        - name: KAFKA_CONSUMER_GROUP
          value: "candles-consumer-group"
        - name: CANDLE_SEC
          value: "60"