apiVersion: apps/v1
kind: Deployment
metadata:
  name: candles
  namespace: rwml 
  labels:
    app: candles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candles
  template:
    metadata:
      labels:
        app: candles
    spec:
      containers:
      - name: candles
        image: ghcr.io/mingsheng92/candles:0.1.5-beta.@sha256:c331362171d2d4b40633e84700e037be9fb404c97d3d6b15fa45b6bce73d5ef7
        imagePullPolicy: Always # pull the latest image from the registry, disregarding the caches that kubernetes may have
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_INPUT_TOPIC
          value: "trades"
        - name: KAFKA_OUTPUT_TOPIC
          value: "candles"
        - name: KAFKA_CONSUMER_GROUP
          value: "candles-consumer-group"
        - name: CANDLE_SEC
          value: "60"